name: Test valuation module
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.platform}}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
      - name: Upload Coverage
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v2